"""
JHU Sponsored Report parser.

Parses the PDF spending reports generated by JHU's SAP-based financial
system for sponsored (grant-funded) projects.  These reports contain a
summary page with cumulative spending by category and subsequent pages
with per-person salary breakdowns.

This parser is registered as an entry point and discovered automatically
when smaug is installed.
"""

from pathlib import Path

from ..models import EffortAllocation, SpendingReport
from ..sponsored_report_parsing import (
    parse_non_sponsored_report as _parse_non_sponsored,
)
from ..sponsored_report_parsing import (
    parse_sponsored_report as _parse_sponsored,
)
from . import ReportParser


class JHUSponsoredParser(ReportParser):
    """Parser for JHU sponsored project PDF reports."""

    def name(self) -> str:
        return "JHU Sponsored Report"

    def can_parse(self, file_path: Path) -> bool:
        """Detect JHU sponsored reports by checking for PDF format and
        JHU-specific markers in the first page text."""
        if file_path.suffix.lower() != ".pdf":
            return False

        try:
            import pdfplumber

            with pdfplumber.open(file_path) as pdf:
                if not pdf.pages:
                    return False
                text = pdf.pages[0].extract_text() or ""
                # JHU sponsored reports contain these markers
                return "Sponsored Program:" in text or (
                    "Grant:" in text and "Expenditures Budget" in text
                )
        except Exception:
            return False

    def parse(self, file_path: Path) -> tuple[SpendingReport | None, list[EffortAllocation]]:
        return _parse_sponsored(file_path)


class JHUNonSponsoredParser(ReportParser):
    """Parser for JHU non-sponsored (discretionary) PDF reports."""

    def name(self) -> str:
        return "JHU Non-Sponsored Report"

    def can_parse(self, file_path: Path) -> bool:
        if file_path.suffix.lower() != ".pdf":
            return False

        try:
            import pdfplumber

            with pdfplumber.open(file_path) as pdf:
                if not pdf.pages:
                    return False
                text = pdf.pages[0].extract_text() or ""
                return "Funded Program:" in text or "Non Sponsored" in text
        except Exception:
            return False

    def parse(self, file_path: Path) -> tuple[SpendingReport | None, list[EffortAllocation]]:
        report = _parse_non_sponsored(file_path)
        return report, []
